// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrFPaydGHsDAff4fS-LlDrVJu2GC0fBN0',
    appId: '1:593625609255:web:df1b6f4431cca7c2338a02',
    messagingSenderId: '593625609255',
    projectId: 'ag-2548f',
    authDomain: 'ag-2548f.firebaseapp.com',
    storageBucket: 'ag-2548f.firebasestorage.app',
    measurementId: 'G-WLC1XM8HSJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKYVHmCKdrtl4U-hZxShhZ4xzlezq_vFo',
    appId: '1:593625609255:android:a44c59a819d96cdd338a02',
    messagingSenderId: '593625609255',
    projectId: 'ag-2548f',
    storageBucket: 'ag-2548f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfgGIq3EyrjdgA4OflN7KpB-SqoN1sRBQ',
    appId: '1:593625609255:ios:a6bf3eac025f9e0d338a02',
    messagingSenderId: '593625609255',
    projectId: 'ag-2548f',
    storageBucket: 'ag-2548f.firebasestorage.app',
    iosBundleId: 'com.example.agsecure',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfgGIq3EyrjdgA4OflN7KpB-SqoN1sRBQ',
    appId: '1:593625609255:ios:a6bf3eac025f9e0d338a02',
    messagingSenderId: '593625609255',
    projectId: 'ag-2548f',
    storageBucket: 'ag-2548f.firebasestorage.app',
    iosBundleId: 'com.example.agsecure',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrFPaydGHsDAff4fS-LlDrVJu2GC0fBN0',
    appId: '1:593625609255:web:a9b96a588805cd34338a02',
    messagingSenderId: '593625609255',
    projectId: 'ag-2548f',
    authDomain: 'ag-2548f.firebaseapp.com',
    storageBucket: 'ag-2548f.firebasestorage.app',
    measurementId: 'G-76ZWX3QW31',
  );
}
