// ignore: depend_on_referenced_packages
//import 'package:capstone/screens/auth_screens.dart';
import 'package:agsecure/firebase_options.dart';
import 'package:agsecure/screens/auth_screens.dart';
import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
// Generated by FlutterFire CLI

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  runApp(const AgriculturalApp());
}

// class DefaultFirebaseOptions {
//   static FirebaseOptions? get currentPlatform => null;
// }

class AgriculturalApp extends StatelessWidget {
  const AgriculturalApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'AgSecure',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primaryColor: const Color(0xFF2D5F2E),
        scaffoldBackgroundColor: const Color(0xFFF5F5F5),
        appBarTheme: const AppBarTheme(
          backgroundColor: Color(0xFF2D5F2E),
          foregroundColor: Colors.white,
        ),
        elevatedButtonTheme: ElevatedButtonThemeData(
          style: ElevatedButton.styleFrom(
            backgroundColor: const Color(0xFF2D5F2E),
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(12),
            ),
            elevation: 3,
            minimumSize: const Size(double.infinity, 56),
          ),
        ),
        inputDecorationTheme: InputDecorationTheme(
          border: OutlineInputBorder(borderRadius: BorderRadius.circular(12)),
        ),
      ),
      home: const AuthScreen(), // Your auth screen
    );
  }
}
